### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by jpmi1** [AlJohri/RedditSync#1]
when looking for new posts in subreddits

Found new Submission:  44pioh Why build attack speed on Jhin, isn't flat AD better?
Found new Submission:  449qm1 Bronze Moments | Episode 47
Found new Submission:  44pks8 What is Reignover's NA account?
Found new Submission:  44otvb Sweetheart Sona by Kairui-chan
Found new Submission:  44ojxw Not even TSM could make Turtle look good!
Found new Submission:  446hka Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\RedditBlogger\redditblogger\monitor_subreddits_and_create_blogposts.py", line 44, in <module>
    print("Found new Submission: ", submission.id, submission.title)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 17: ordinal not in range(128)

**Comment by jpmi1** [comment]
same error on new verision
Found new Submission:  450kg2 ☾Katlife☽ Master Tier Katarina Montage 5
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/RedditBlogger/redditblogger/monitor_subreddits_and_create_blogposts.py", line 58, in <module>
    print("Writing submission [%s %s] to blog %s for subreddit %s" % (submission.id, submission.title.encode('utf-8'), blog_id, subreddit_name))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

**Comment by jpmi1** [comment]
This error is a duplicate of the asci error closing
